global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8888']

  - job_name: da-node-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8889']
